cc_test(
    name = "arith-test",
    srcs = ["testGR.cc",
            "testGR.cc"
            ],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//main:galois-ring",
    ],
)

