# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "galois_ring"
version = "0.1.0"
description = "math library"

[cmake]
version = "3.15"
cmkr-include = "cmkr.cmake"

# [dependencies]
# cmake = ">=3.15"


# fecth a content
# [fetch-content]
# fmt = { git = "https://github.com/fmtlib/fmt", tag = "7.1.3" }

# [target.xkcp]
# type = "static"
# include-directories = ["third_party/XKCP/libxkcp.a.headers"]
# link-libraries = ["third_party/XKCP/libxkcp.a"]


[target.grlib]
type = "interface"
include-directories = ["lib"]
headers = ["lib/gring.h", "lib/grlifttables.h", "lib/grmodtables.h"]
compile-features = ["cxx_std_20"]



[target.saccheck]
type = "executable"
headers = ["lib/random.h", "lib/saccheck.h"]
# TODO: sources = ["lib/saccheck.cc"]
include-directories = ["third_party/XKCP/libxkcp.a.headers"]
link-libraries = ["third_party/XKCP/libxkcp.a", "grlib"]
compile-features = ["cxx_std_20"]

# [target.demo]
# type = "executable"
# sources = ["main/demo.cpp"]
# link-libraries = ["grlib"]


[target.grtowertest]
type = "executable"
headers = [#"Test/UnitTests/GaloisRingTowering/testGRTowering.inc",
           "test/UnitTests/UnitTest.h",
           "test/UnitTests/GaloisRingTowering/testGRTowering.h",]
sources = ["test/UnitTests/UnitTest.cc", "test/UnitTests/GaloisRingTowering/testGRTowering.cc"]
link-libraries = ["grlib"]
compile-features = ["cxx_std_20"]


[target.grtest]
type = "executable"
headers = ["test/UnitTests/UnitTest.h",
           "test/UnitTests/GaloisRing/testGR.h",]
sources = ["test/UnitTests/UnitTest.cc", "test/UnitTests/GaloisRing/testGR.cc"]
link-libraries = ["grlib"]
compile-features = ["cxx_std_20"]


[target.grbenchmark]
type = "executable"
sources = ["src/benchmark_GR.cc"]
link-libraries = ["grlib"]
compile-features = ["cxx_std_20"]














