# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "galois_ring"
version = "0.1.0"
description = "math library"


# [dependencies]
# cmake = ">=3.15"


# fecth a content
# [fetch-content]
# fmt = { git = "https://github.com/fmtlib/fmt", tag = "7.1.3" }


[target.grlib]
type = "interface"
include-directories = ["lib"]
headers = ["lib/gring.h", "lib/grlifttables.h", "lib/grmodtables.h"]
compile-features = ["cxx_std_20"]

# [target.demo]
# type = "executable"
# sources = ["main/demo.cpp"]
# link-libraries = ["grlib"]


[target.grtowertest]
type = "executable"
headers = [#"Test/UnitTests/GaloisRingTowering/testGRTowering.inc",
           "Test/UnitTests/UnitTest.h",
           "Test/UnitTests/GaloisRingTowering/testGRTowering.h",]
sources = ["Test/UnitTests/UnitTest.cc", "Test/UnitTests/GaloisRingTowering/testGRTowering.cc"]
link-libraries = ["grlib"]
compile-features = ["cxx_std_20"]












