# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "galois_ring"
version = "0.1.0"
description = "math library"


# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/galois_ring/*.cpp", "include/galois_ring/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]

[dependencies]
cmake = ">=3.15"


# fecth a content
# [fetch-content]
# fmt = { git = "https://github.com/fmtlib/fmt", tag = "7.1.3" }


[target.grlib]
type = "interface"
include-directories = ["lib"]
sources = ["lib/**.h"]
compile-features = ["c++_std_20"]


[target.demo]
type = "executable"
sources = ["main/demo.cpp"]
link-libraries = ["grlib"]


[target.test]
type = "executable"
sources = ["Test/UnitTest"]
link-libraries = ["grlib"]






